name: Changelog
on:
  release:
    types:
    - created
  push:
    branches:
      - changelog

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "Generate release changelog"
        id: gen
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish binary
        uses: actions/upload-artifact@v2
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md
